### ISSUE TITLE
AttributeError: function 'LLVMPY_LoadLibraryPermanently' not found

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/blaze#959] opened 2015-02-21 16:33 UTC
```
import blaze
```

Results in the following error:
```
AttributeError: function 'LLVMPY_LoadLibraryPermanently' not found
```

Installed blaze in new conda environment with:
```
conda create -n blaze_test -c blaze -c numba blaze numba pip

blaze                     0.7.2                np19py27_0
blaze-core                0.7.2                np19py27_0
llvmlite                  0.3.0                   py27_12
numba                     0.17.0             np19py27_121
```

**Comment by mrocklin** [comment] 2015-02-21 17:54
cc @seibert @sklam @cpcloud

**Comment by pitrou** [comment] 2015-02-23 16:27
Works for me under Linux. Are you under Windows?

**Comment by ARF1** [comment] 2015-02-25 17:09
@pitrou Indeed, I am on Windows 8.1

**Comment by gmarkall** [comment] 2015-02-25 17:42
It looks like llvmlite has an outdated extension module for some reason. Try closing all Python interpreters (or restarting the machine) and running:

```
conda install -c numba --force llvmlite
```

to see if that resolves the issue.

**Comment by ARF1** [comment] 2015-02-25 19:18
@gmarkall That seems to have helped. Thank you very much. Still not sure, why this problem occurred in the first place... It seems however, that I installed blaze and llvmlite using separate `conda install` commands. 

In case this problem does not go away by its own in future releases and needs to be debugged, here is my revisions log to reproduce the error:
```
[blaze_test] C:\Users\Example User>conda list -r
2015-02-21 16:41:56  (rev 0)

2015-02-21 16:43:46  (rev 1)
    +bcolz-0.8.0
    +blaze-0.7.2
    +blaze-core-0.7.2
    +cytoolz-0.7.1
    +datashape-0.4.3
    +dateutil-2.1
    +decorator-3.4.0
    +enum34-1.0.4
    +flask-0.10.1
    +funcsigs-0.4
    +h5py-2.4.0
    +into-0.2.2
    +itsdangerous-0.24
    +jinja2-2.7.3
    +llvmlite-0.2.2
    +markupsafe-0.23
    +multipledispatch-0.4.7
    +networkx-1.9.1
    +numba-0.17.0
    +numexpr-2.3.1
    +numpy-1.9.1
    +pandas-0.15.2
    +pip-6.0.8
    +psutil-2.2.0
    +pymongo-2.8
    +pytables-3.1.1
    +python-2.7.9
    +pytz-2014.9
    +requests-2.5.1
    +scipy-0.15.1
    +setuptools-12.2
    +six-1.9.0
    +sqlalchemy-0.9.8
    +toolz-0.7.1
    +werkzeug-0.10.1

2015-02-21 16:50:20  (rev 2)
    +ipython-2.4.1
    +pyreadline-2.0

2015-02-21 16:51:08  (rev 3)
    +pyzmq-14.5.0

2015-02-21 16:58:11  (rev 4)
    +matplotlib-1.4.3
    +pyparsing-2.0.3
    +pyqt-4.10.4

2015-02-21 17:02:53  (rev 5)
    +future-0.14.3

2015-02-21 17:07:31  (rev 6)
     llvmlite  {0.2.2 -> 0.3.0}
     numba  {0.17.0 -> 0.17.0}


[blaze_test] C:\Users\Example User>
```

**Comment by gmarkall** [comment] 2015-02-25 19:57
@ARF1 thanks for the details. I suspect that this is a known issue with conda on Windows that's being worked on - as I understand it, https://github.com/conda/conda/pull/1133 is a related PR for the root cause of issues like this.

**Closed** 2015-02-25 20:49 UTC
