### ISSUE TITLE
Data() not working

### ISSUE THREAD

**Issue by an100** [ContinuumIO/blaze#1008] opened 2015-03-29 20:40 UTC
I am following the doc. t = Data() does not work...

```
from blaze import *

In [41]:

print blaze.__version__

0.6.3

In [40]:

t = Data([(1, 'Alice', 100),

          (2, 'Bob', -200),

          (3, 'Charlie', 300),

          (4, 'Denis', 400),

          (5, 'Edith', -500)],

         fields=['id', 'name', 'balance'])

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-40-a99642278eac> in <module>()
----> 1 t = Data([(1, 'Alice', 100),
      2           (2, 'Bob', -200),
      3           (3, 'Charlie', 300),
      4           (4, 'Denis', 400),
      5           (5, 'Edith', -500)],

NameError: name 'Data' is not defined
```

**Comment by cpcloud** [comment] 2015-03-30 00:00
closing as not a bug

**Closed by cpcloud** 2015-03-30 00:00 UTC
Labels: question
